### ISSUE TITLE
Error message only on email label

### ISSUE THREAD

**Issue by ciarangaffey** [scdoshi/jquery-ajaxchimp#26]
Hi there,

First off thanks for creating this awesome plugin. 
I'm having an issue where the error message (Please enter a value) is only appearing on the email label (mc-email). The error message appears when the other required fields are not filled in, but only on the email label.
How do I make the error message appear for the other required fields on my form? Is there a way of making ajaxchimp recognise the required labels other than mc-email?

Thanks!

**Comment by scdoshi** [comment]
Unfortunately, this plugin currently only covers forms with just the email field. Because of this, all error messages returned are assumed to be for the email field.

You can of course override this behaviour via the callback or by changing the javascript source. If you do make a change and want it to be included in the default plugin, please make a pull request.
