### ISSUE TITLE
Please add code to also capture "name" along with "email"

### ISSUE THREAD

**Issue by gabriella8** [scdoshi/jquery-ajaxchimp#28]
Hi Sid, 
Thanks for this great plugin! 
I am not a coder and I tried to figure out how to also capture the user's name along with the email. It's there in my html, but I think the jquery plugin also needs to collect this information so that it's sent to MC? 
What is the piece of code that needs to be added for that? 

Thank you soooo much for your help! 
Gabriella

**Comment by danielemesh** [comment]
Is there a fix for this issue?

**Comment by scdoshi** [comment]
The way the code is written, the ajax call should be submitting all form elements. I can think of two issues:

1) Your name fields do not have the correct `name` attribute that MC expects
2) MC is not accepting the `name` attribute via this type of a call (It IS an undocumented feature, and I haven't tested more than the email field. (#26 suggests otherwise however)
