### ISSUE TITLE
Subscription without double opt-in ?

### ISSUE THREAD

**Issue by developositivo** [scdoshi/jquery-ajaxchimp#30]
Is there some param that I could pass into ajax function to avoid the double opt-in ? I've read into the mailchimp docs that it's not possible to customize the email confirmation template, that's possible only for the "welcome email", but it would be wonderful to make the subscription without confirmation. I know that's possible to make it throught the api, via php, but I'm not so familiar with ajax, and maybe there is a way to improve the plugin adding that functionality.

Can someone help??

**Comment by JonathanWi** [comment]
@developositivo it is possible to style the opt-in email (put your logo, customize color and text). However it seems impossible to avoid double opt-in, mainly for safety reasons.

**Comment by RobLoach** [comment]
Grr, Mailchimp.

**Comment by scdoshi** [comment]
It doesn't make sense for allow subscription via Ajax without confirmation, because them anyone could sign up any number of email addresses on your mailing list, leading your entire list to be marked as spam.

This is bad for you and bad for MC.

When you do it via the API, you are using your API credentials, and so hopefully going through your backend where you can have more control over what's happening.
