### ISSUE TITLE
Not sure how to use callback

### ISSUE THREAD

**Issue by mwickett** [scdoshi/jquery-ajaxchimp#4]
I'm a total n00b and know just barely enough to be frighteningly dangerous. Thanks for making this, it's super helpful.

I'm struggling with how to get a success ("Check your email to confirm") message to show once they're successfully subscribed.

Could you post an example of exactly how the callback function would be used? I know you've probably got better things to do, but even if you could point me in the right direction, I'd really appreciate it.

**Comment by scdoshi** [comment]
It seems mailchimp stopped allowing cross-domain requests, so the plugin does not work anymore. Please double check your website if you were using it

**Comment by scdoshi** [comment]
Hi @mwickett,

If you have a label element for the email input on the form, the success/error messages will automatically show in the label.

```
<form id="mc-form">
    <input id="mc-email" type="email" placeholder="email">
    <label for="mc-email"></label>
    <button type="submit">Submit</button>
</form>
```

If you want to show it in a different place, then you can use the callback function to do so, but you do not need to specify a callback otherwise.

To use the callback, you would create a function that receives the response data as an argument, and do whatever DOM manipulation to display the message in the function.

Pass in the function name as the callback when initializing ajaxchimp, and it will automatically be called after someone submits an email address.

**Comment by scdoshi** [comment]
Also, disregard the message about the plugin not working anymore, it was a mistake on my part. The plugin works just fine.
